# playbook.yml:
---
- name: "Ubuntu laptop optimizations"
  hosts: 127.0.0.1
  connection: local
  become: true
  gather_facts: no
  tasks:

    - name: Remove laptop-mode-tools
      apt: 
        name:
          - laptop-mode-tools
        state: absent

    - name: Add tlp repository
      apt_repository:
        repo: ppa:linuxuprising/apps
        state: present

    - name: Update apt
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Install tlp
      apt: 
        name:
          - tlp
          - tlpui
        state: latest
