---
- name: "Ubuntu desktop playbook"
  hosts: "common"
  connection: local
  become: true
  gather_facts: no
  tasks:

    - name: Update apt
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Remove unnecessary packages
      apt: 
        name:
          - brltty
          - apache2
        state: absent

    - name: Install common packages
      apt: 
        name:
          - alacarte
          - ca-certificates
          - firefox
          - git
          - git-flow
          - git-lfs
          - gnome-tweaks
          - htop
          - lnav
          - lsb-release
          - make
          - mc
          - ncdu
          - net-tools
          - nethogs
          - p7zip
          - pydf
          - synaptic
          - ubuntu-restricted-extras
          - vokoscreen
          - wget
          - tigervnc-viewer
          - fonts-ubuntu-classic
          - totem
          - gdu
        state: latest

    - name: Enabel ufw
      ufw:
        state: enabled
