# playbook.yml:
---
- name: "Ubuntu virtualbox"
  hosts: "virtualbox"
  connection: local
  become: true
  gather_facts: yes
  tasks:

    - name: Install virtualbox
      expect:
        command: apt-get install virtualbox virtualbox-ext-pack
        responses:
          Question:
            - 'Y'
            - 'n'

    - name: Add current user into vboxusers group
      shell: usermod -aG vboxusers `logname`
