# playbook.yml:
---
- name: "Ubuntu golang"
  hosts: "golang"
  connection: local
  become: true
  gather_facts: yes

  vars:
    golang_user: "{{ ansible_facts['env']['SUDO_USER'] }}"
    golang_home: "/home/{{ golang_user }}"

  tasks:

    - name: Remove old installation from source
      file:
        path: /usr/local/go
        state: absent

    - name: Add golang repository
      apt_repository:
        repo: ppa:longsleep/golang-backports
        state: present

    - name: Update apt
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install golang
      apt: 
        name:
          - golang-go
        state: latest

    - name: Modify .bashrc in the {{ golang_home }}
      blockinfile:
        dest: "{{ golang_home }}/.bashrc"
        block: |
          export PATH=$PATH:{{ golang_home }}/go/bin
        marker: '# {mark} ANSIBLE MANAGED BLOCK - Golang'
        insertafter: EOF
        create: yes
        state: present

