# playbook.yml:
---
- name: "Ubuntu visual studio code"
  hosts: 127.0.0.1
  connection: local
  become: true
  gather_facts: no
  tasks:

    - name: Install backend packages
      apt: 
        name:
          - apt-transport-https
        state: latest

    - name: Add microsoft signing key
      apt_key:
        url: "https://packages.microsoft.com/keys/microsoft.asc"
        state: present

    - name: Add vscode repository into sources list
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        state: present

    - name: Install vscode
      apt:
        name:
          - code
        state: latest
