---
- name: "Ubuntu samba"
  hosts: "samba"
  connection: local
  become: true
  gather_facts: no
  tasks:

    - name: Install samba packages
      apt: 
        name:
          - samba
          - smbclient 
          - gvfs 
          - gvfs-backends 
          - dbus-x11
        state: latest

    - name: Enable support old protocol
      shell: "sed -i 's/^\[global\]/[global]\n client min protocol = NT1\n server min protocol = NT1/g' /etc/samba/smb.conf"

    - name: Restart samba services
      service:
        name: {{ item }}
        state: restarted
      with_items:
        - smbd
        - nmbd

    - name: Enable ufw
      ufw:
        state: enabled

    - name: Allow samba
      ufw:
        rule: allow
        name: Samba

    - name: Allow samba for home networks
      ufw:
        rule: allow
        name: Samba
        src: "{{ item }}"
      with_items: "{{ samba_networks }}"
