---
- name: "Ubuntu firewall playbook"
  hosts: "ufw"
  connection: local
  become: true
  gather_facts: no
  tasks:

    - name: Reset ufw
      ufw:
        state: reset

    - name: Enable ufw
      ufw:
        state: enabled
