# playbook.yml:
---
- name: "My ubuntu laptop playbook"
  hosts: 127.0.0.1
  connection: local
  become: true
  gather_facts: no
  tasks:

    - name: Remove apt docker
      apt: 
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent

    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Install requirements
      apt: 
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest

    - name: Add docker repo
      shell: |
        echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Install docker
      apt: 
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Add docker group
      shell: |
        groupadd docker
        usermod -aG docker `logname`

    - name: Install docker-compose
      shell: |
        cd /tmp
        wget https://github.com/docker/compose/releases/download/v2.1.1/docker-compose-linux-x86_64
        mv ./docker-compose-linux-x86_64 /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
  